(* Nathan Burgers 2014 *)

(* structure Disj : Disj = struct *)
(* open Maybe *)
(* datatype ('a, 'b) t *)
(*   = A of 'a *)
(*   | B of 'b *)
(* fun left t = case t of *)
(* 		 A a => Just a *)
(* 	       | B b => None *)
(* fun right t = case t of *)
(* 		  A a => None *)
(* 		| B b => Just b  *)
(* end *)
